name: Android Build

on:
  push:
    branches: [ workflows ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report.html
          path: app/build/reports/lint-results-debug.html